# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(965, 447)
        self.btnSend = QtWidgets.QPushButton(Dialog)
        self.btnSend.setGeometry(QtCore.QRect(290, 390, 93, 31))
        self.btnSend.setObjectName("btnSend")
        self.btnConnect = QtWidgets.QPushButton(Dialog)
        self.btnConnect.setGeometry(QtCore.QRect(290, 30, 93, 28))
        self.btnConnect.setCheckable(True)
        self.btnConnect.setObjectName("btnConnect")
        self.cmbCOM = QtWidgets.QComboBox(Dialog)
        self.cmbCOM.setGeometry(QtCore.QRect(90, 60, 111, 22))
        self.cmbCOM.setObjectName("cmbCOM")
        self.btnUpdate = QtWidgets.QPushButton(Dialog)
        self.btnUpdate.setGeometry(QtCore.QRect(290, 60, 93, 28))
        self.btnUpdate.setObjectName("btnUpdate")
        self.cmbBAUD = QtWidgets.QComboBox(Dialog)
        self.cmbBAUD.setGeometry(QtCore.QRect(90, 30, 111, 22))
        self.cmbBAUD.setObjectName("cmbBAUD")
        self.txtSend = QtWidgets.QTextEdit(Dialog)
        self.txtSend.setGeometry(QtCore.QRect(20, 390, 251, 31))
        self.txtSend.setObjectName("txtSend")
        self.lstView = QtWidgets.QTextBrowser(Dialog)
        self.lstView.setGeometry(QtCore.QRect(20, 150, 361, 221))
        self.lstView.setObjectName("lstView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 120, 201, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(420, 10, 511, 411))
        self.groupBox.setObjectName("groupBox")
        self.viewCamera = QtWidgets.QLabel(self.groupBox)
        self.viewCamera.setGeometry(QtCore.QRect(20, 20, 471, 341))
        self.viewCamera.setFrameShape(QtWidgets.QFrame.Box)
        self.viewCamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewCamera.setLineWidth(6)
        self.viewCamera.setObjectName("viewCamera")
        self.btnCamera = QtWidgets.QPushButton(self.groupBox)
        self.btnCamera.setGeometry(QtCore.QRect(220, 370, 93, 28))
        self.btnCamera.setObjectName("btnCamera")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSend.setText(_translate("Dialog", "SEND"))
        self.btnConnect.setText(_translate("Dialog", "CONNECT"))
        self.btnUpdate.setText(_translate("Dialog", "Update"))
        self.label.setText(_translate("Dialog", "Baudrate"))
        self.label_2.setText(_translate("Dialog", "COM port"))
        self.label_3.setText(_translate("Dialog", "Comunication with STM32F103C8"))
        self.groupBox.setTitle(_translate("Dialog", "                                                        CAMERA"))
        self.viewCamera.setText(_translate("Dialog", "TextLabel"))
        self.btnCamera.setText(_translate("Dialog", "ON CAMERA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
